services:
  pg:
    image: postgres:17
    container_name: cloneugc-pg
    environment:
      POSTGRES_DB: cloneugc
      POSTGRES_USER: cloneugc
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cloneugc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
