services:
  pg:
    image: postgres:17.5
    container_name: cloneugc-pg
    environment:
      POSTGRES_USER: cloneugc
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
