[project]
name = "cloneugc"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]>=5.5.2",
    "django>=5.2.1",
    "django-storages[s3]>=1.14.6",
    "gunicorn>=23.0.0",
    "requests>=2.32.3",
    "whitenoise[brotli]>=6.9.0",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.1.0",
    "ruff>=0.11.11",
]

[tool.ruff.lint]
extend-select = ["I", "F401"]
