[project]
name = "cloneugc"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "gunicorn>=23.0.0",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.1.0",
    "ruff>=0.11.11",
]

[tool.ruff.lint]
extend-select = ["I", "F401"]
