# Generated by Django 5.2.1 on 2025-06-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
