# Generated by Django 5.2.1 on 2025-05-23 00:46

from django.db import migrations, models

import cloneugc.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=cloneugc.utils.shortid,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
