# Generated by Django 5.2.1 on 2025-05-23 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloneugc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
