# Generated by Django 5.2.1 on 2025-05-25 00:00

from django.db import migrations, models

import cloneugc.models


class Migration(migrations.Migration):
    dependencies = [
        ("cloneugc", "0008_alter_generation_lipsync_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="generation",
            name="video",
            field=models.FileField(null=True, upload_to=cloneugc.models.instance_path),
        ),
    ]
