# Generated by Django 5.2.1 on 2025-05-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_creator_video_mp4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='video_mp4',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=''),
        ),
    ]
