# Generated by Django 5.2.1 on 2025-05-23 22:45

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_actor_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="video",
            field=models.FileField(default="", upload_to=api.models.instance_path),
            preserve_default=False,
        ),
    ]
