# Generated by Django 5.2.1 on 2025-05-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_actor_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="voice_id",
            field=models.TextField(null=True),
        ),
    ]
