# Generated by Django 5.2.1 on 2025-05-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_generation_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="generation",
            name="lipsync_request_id",
            field=models.TextField(null=True),
        ),
    ]
