# Generated by Django 5.2.1 on 2025-05-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_generation_lipsync_request_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generation",
            name="lipsync_request_id",
            field=models.TextField(null=True, unique=True),
        ),
    ]
