# Generated by Django 5.2.1 on 2025-05-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_generation_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generation",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting_processing", "Waiting Processing"),
                    ("cloning_voice", "Cloning Voice"),
                    ("generating_audio", "Generating Audio"),
                    ("syncing_lips", "Syncing Lips"),
                    ("saving_video", "Saving Video"),
                    ("completed", "Completed"),
                ],
                default="waiting_processing",
                max_length=20,
            ),
        ),
    ]
