# Generated by Django 5.2.1 on 2025-05-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ugc',
            options={'verbose_name': 'UGC', 'verbose_name_plural': 'UGCS'},
        ),
    ]
