# Generated by Django 5.2.1 on 2025-05-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0003_alter_creator_video_mp4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="video",
            field=models.FileField(upload_to="booth/creators/videos"),
        ),
    ]
