# Generated by Django 5.2.1 on 2025-06-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0008_alter_creator_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='tags',
        ),
    ]
