# Generated by Django 5.2.1 on 2025-06-03 17:21

import lib.shortid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth", "0009_remove_creator_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="id",
            field=models.CharField(
                default=lib.shortid.shortid,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
