# Generated by Django 5.2.1 on 2025-05-26 04:17

import django.db.models.deletion
from django.db import migrations, models

import cloneugc.api.models
import cloneugc.api.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=cloneugc.api.utils.shortid,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "video",
                    models.FileField(upload_to=cloneugc.api.models.instance_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voice_id", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=cloneugc.api.utils.shortid,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        null=True, upload_to=cloneugc.api.models.instance_path
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        null=True, upload_to=cloneugc.api.models.instance_path
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_processing", "Waiting Processing"),
                            ("cloning_voice", "Cloning Voice"),
                            ("generating_audio", "Generating Audio"),
                            ("syncing_lips", "Syncing Lips"),
                            ("saving_video", "Saving Video"),
                            ("completed", "Completed"),
                        ],
                        default="waiting_processing",
                        max_length=20,
                    ),
                ),
                ("lipsync_request_id", models.TextField(null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.actor"
                    ),
                ),
            ],
        ),
    ]
