# Generated by Django 5.2.1 on 2025-05-24 23:20

import django.db.models.deletion
from django.db import migrations, models

import cloneugc.utils


class Migration(migrations.Migration):
    dependencies = [
        ("cloneugc", "0004_actor_voice_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=cloneugc.utils.shortid,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cloneugc.actor"
                    ),
                ),
            ],
        ),
    ]
