# Generated by Django 5.2.1 on 2025-05-24 23:23

from django.db import migrations, models

import cloneugc.models


class Migration(migrations.Migration):
    dependencies = [
        ("cloneugc", "0005_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="generation",
            name="audio",
            field=models.FileField(null=True, upload_to=cloneugc.models.instance_path),
        ),
    ]
