# Generated by Django 5.2.1 on 2025-05-30 13:17

from django.db import migrations, models

import shortid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.CharField(
                default=shortid.shortid,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
