# Generated by Django 5.2.1 on 2025-05-28 04:19

import django.db.models.deletion
import shortid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UGC",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortid.shortid,
                        editable=False,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("script", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="booth.creator",
                    ),
                ),
            ],
        ),
    ]
