# Generated by Django 5.2.1 on 2025-05-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0003_ugc_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="ugc",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="ugc/audios/"),
        ),
    ]
